sudo: false
language: ruby
cache: bundler

rvm:
  - ruby-head
  - 2.7.0-preview1
  - 2.6.3
  - 2.5.5
  - 2.4.6
  - 2.3.8

gemfile:
  - gemfiles/openssl_head.gemfile
  - gemfiles/openssl_2_1.gemfile
  - gemfiles/openssl_2_0.gemfile
  - gemfiles/openssl_default.gemfile

before_install: gem install bundler -v '~> 1.17'

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.7.0-preview1
    - gemfile: gemfiles/openssl_head.gemfile
