sudo: false
language: ruby
cache: bundler

os:
  - linux
  - osx

rvm:
  - ruby-head
  - 2.6.5
  - 2.5.7
  - 2.4.9
  - 2.3.8

gemfile:
  - gemfiles/openssl_head.gemfile
  - gemfiles/openssl_2_1.gemfile
  - gemfiles/openssl_2_0.gemfile
  - gemfiles/openssl_default.gemfile

before_install:
  - gem install bundler -v '~> 2.0'
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./script/setup-osx; else sudo ./script/setup-linux; fi

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - gemfile: gemfiles/openssl_head.gemfile
