sudo: false
language: ruby

rvm:
  - ruby-head
  - 2.6.2
  - 2.5.5
  - 2.4.6
  - 2.3.8
  - 2.2.10

gemfile:
  - gemfiles/openssl_2_0.gemfile
  - gemfiles/openssl_2_1.gemfile
  - gemfiles/openssl_default.gemfile

before_install: gem install bundler -v 2.0.1

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: 2.3.8
    - rvm: 2.2.10
